config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  
  get "/signup", to: "users#new"
  resources :users, only: [:create]
  
  get "/login", to: "sessions#new"
  post "/sessions", to: "sessions#create"
  delete "/sessions", to: "sessions#destroy"
  
  get '/dashboard', to: 'dashboard#index'
  
  resources :projects, except: [:index]
  resources :issues, except: [:index]
  resources :comments, only: [:create]
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	validates :issue_id, :commenter_id, :content, presence: true
	
	belongs_to :issue
	belongs_to :commenter, primary_key: :id, foreign_key: :commenter_id,
		class_name: :User
end

app/models/issue.rb
class Issue < ApplicationRecord
	validates :project_id, :reporter_id, :subject, presence: true
	PRIORITIES = %w(Low Medium High Urgent)
	validates :priority, inclusion: { in: PRIORITIES }
	STATUSES = %w(New Assigned Feedback Acknowledged Resolved Closed)
	validates :status, inclusion: { in: STATUSES }
	
	belongs_to :project
	belongs_to :reporter, primary_key: :id, foreign_key: :reporter_id,
		class_name: :User
	belongs_to :assignee, primary_key: :id, foreign_key: :assignee_id,
		class_name: :User, optional: true
	has_many :comments, dependent: :destroy
end

app/models/project.rb
class Project < ApplicationRecord
	validates :name, presence: true, uniqueness: { case_sensitive: false }
	STATUSES = %w(Development Test Production Obsolete)
	validates :status, inclusion: { in: STATUSES }
	
	has_many :issues, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
  validates :name, presence: true
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates :password, :password_confirmation, length: { minimum: 1, allow_nil: true }
  
  has_many :reported_issues, primary_key: :id, foreign_key: :reporter_id,
  	class_name: :Issue, dependent: :destroy
  has_many :assigned_issues, primary_key: :id, foreign_key: :assignee_id,
  	class_name: :Issue, dependent: :destroy
  has_many :comments, primary_key: :id, foreign_key: :commenter_id,
  	class_name: :Comment, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	helper_method :logged_in?, :current_user

  def current_user
    if session[:user_id]
      @user = User.find(session[:user_id])
    end
  end

  def logged_in?
    !!current_user
  end

  def authorized
    redirect_to login_path unless logged_in?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	before_action :authorized
	
	def create
		@comment = Comment.new(comment_params)
		respond_to do |format|
			if @comment.save
				format.json { render json: { status: :created } }
			else
				format.json { render json: @comment.errors,
					status: :unprocessable_entity }
			end
		end
	end
	
	private
	
	def comment_params
		params.require(:comment).permit(:issue_id, :commenter_id, :content)
	end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

	before_action :authorized
	
  def index
  	@user = current_user
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	if logged_in?
  		redirect_to dashboard_path
  	end
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
	
	before_action :authorized
	
	def new
		@issue = Issue.new
		@issue.reporter_id = current_user.id
	end
	
	def create
		@issue = Issue.new(issue_params)
		@issue.reporter_id = current_user.id
		if @issue.save
			redirect_to issue_path(@issue)
    else
    	flash[:errors] = @issue.errors.full_messages
      redirect_to new_issue_path
    end
	end
	
	def show
		@issue = Issue.find(params[:id])
		@comments = []
		@issue.comments.each do |comment|
			object = {}
			object['id'] = comment.id
			object['commenter'] = comment.commenter.name
			object['content'] = comment.content
			object['created_at'] = comment.created_at
			@comments << object
		end
		@new_comment = Comment.new
		@new_comment.issue_id = @issue.id
		@new_comment.commenter_id = current_user.id
	end
	
	def edit
    @issue = Issue.find(params[:id])
  end

  def update
    @issue = Issue.find(params[:id])
    if @issue.update_attributes(issue_params)
    	redirect_to issue_path(@issue)
    else
    	flash[:errors] = @issue.errors.full_messages
      redirect_to edit_issue_path(@issue)
    end
  end
	
	def destroy
		@issue = Issue.find(params[:id])
		if @issue.destroy
			redirect_to dashboard_path
		else
			flash[:errors] = @issue.errors.full_messages
			redirect_to issue_path(@issue)
		end
	end
	
	private
	
	def issue_params
		params.require(:issue).permit(:project_id, :reporter_id, :assignee_id,
			:priority, :status, :subject, :description, :due_date)
	end
	
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

	before_action :authorized

	def new
		@project = Project.new
	end
	
	def create
		@project = Project.new(project_params)
		if @project.save
      redirect_to project_path(@project)
    else
      flash[:errors] = @project.errors.full_messages
      redirect_to new_project_path
    end
	end
	
	def show
		@project = Project.find(params[:id])
	end
	
	def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(project_params)
      redirect_to project_path(@project)
    else
      flash[:errors] = @project.errors.full_messages
      redirect_to edit_project_path(@project)
    end
  end
	
	def destroy
		@project = Project.find(params[:id])
		if @project.destroy
			redirect_to dashboard_path
		else
			flash[:errors] = @project.errors.full_messages
			redirect_to project_path(@project)
		end
	end
	
	private
	
	def project_params
		params.require(:project).permit(:name, :status, :description)
	end
	
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to dashboard_path
    else
    	flash[:notice] = 'One or more fields is missing or incorrect.'
      redirect_to login_path
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :authorized, only: [:show]
	
	def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.valid?
      @user.save
      session[:user_id] = @user.id
      redirect_to dashboard_path
    else
    	flash[:errors] = @user.errors.full_messages
      redirect_to signup_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.html.erb
<div class='a-project-div'>
	<hr>
	<div class='dash-projects-header'>
		<div></div>
		<h2>Comments</h2>
		<div></div>
	</div>
	<%= content_tag :div,
			id: 'vuejs',
			data: { comments: @comments, new_comment: @new_comment } do %>
		<div v-for='comment in comments' :key='comment.id'>
			<div class='comment-header'>
				<p>{{ comment.commenter }} says,</p>
				<p>{{ creationTime(comment) }}</p>
			</div>
			<p class='comment-content'>{{ comment.content }}</p>
			<hr>
		</div>
		<label class='new-comment-label'>New Comment</label>
		<br>
		<p class='auth-missing new-project-missing' v-show='error'>{{ error }}</p>
		<textarea v-model='newComment.content'></textarea>
		<br>
		<button @click='addComment'>Add Comment</button>
	<% end %>
</div>

app/views/dashboard/index.html.erb
<%= render "layouts/header" %>

<div class='dash-header'>
	<h1 class='dash-h1'>Welcome, <%= @user.name %></h1>
	<hr>
</div>

<div class='dash-container'>

	<div class='dash-projects'>
		<div class='dash-projects-header'>
			<div></div>
			<h2>Projects</h2>
			<%= button_to "+", new_project_path, method: :get %>
		</div>
		<hr>
		<ul>
			<% Project.order('updated_at desc').each do |project| %>
				<a class='dash-project-link' href='/projects/<%= project.id %>'>
					<%= project.name %>
				</a>
				<p class='dash-project-description'><%= project.description %></p>
				<hr>
			<% end %>
		</ul>
		<a class='dash-create-link dash-project-link' href='/projects/new'>
			Create New Project
		</a>
	</div>
	
	<div class='dash-projects'>
		<div class='dash-projects-header'>
			<div></div>
			<h2>Issues</h2>
			<%= button_to "+", new_issue_path, method: :get %>
		</div>
		<hr>
		<ul>
			<% Issue.order('updated_at desc').each do |issue| %>
				<a class='dash-project-link' href='<%= issue_path(issue) %>'>
					<%= issue.subject %>
				</a>
				<p class='dash-project-description'>
					Status: <%= issue.status %> <span class='dash-separator'>|</span> 
					Priority: <%= issue.priority %> <span class='dash-separator'>|</span> 
					Reported By: <%= User.find(issue.reporter_id).name %>
				</p>
				<hr>
			<% end %>
		</ul>
		<a class='dash-create-link dash-project-link' href='/issues/new'>
			Create New Issue
		</a>
	</div>
	
</div>

app/views/home/index.html.erb
<div class='home-background' id='home-top'>
	<%= render "layouts/header" %>
	<div class='home-section-1'>
		<h1 class='home-h1'>Get Things Done</h1>
		<hr>
		<p class='home-p-1'>With this simple yet productive issue tracker, you and your team can manage projects and tasks quickly and effectively!</p>
		<br>
		<a class='home-arrow-1' href='#home-middle'>
			Learn More <span class="chevron bottom"></span>
		</a>
	</div>
</div>

<div id='home-middle'>
	<h2>It's as easy as 1-2-3!</h2>
	<br>
	<div class='home-steps'>
		<div class='home-step-1'>
			<%= image_tag 'project.png', alt: 'project icon' %>
			<br><br>
			<p>Create a project</p>
			<hr>
			<p>Establish the purpose and objectives of a project in a central location.</p>
		</div>
		<span class="chevron right"></span>
		<div class='home-step-2'>
			<%= image_tag 'issue.png', alt: 'issue icon' %>
			<br><br>
			<p>Create an issue ticket</p>
			<hr>
			<p>Document issues experienced and tasks to be completed throughout the duration of the project.</p>
		</div>
		<span class="chevron right"></span>
		<div class='home-step-3'>
			<%= image_tag 'comment.png', alt: 'comment icon' %>
			<br><br>
			<p>Comment as you work</p>
			<hr>
			<p>Track the progress of issues and collaborate with team members more effectively.</p>
		</div>
	</div>
</div>

<div class='home-bottom'>
	<p>What are you waiting for? Let's get started.</p>
	<br><br>
	<a class='home-arrow-1 gray-border' href='/signup'>
		Sign Up
	</a>
	<br><br><br>
	<hr>
	<footer>
		<p class='home-created-by'>Created by Peter Tran</p>
		<br>
		<a class='home-arrow-1 home-back-to-top' href='#home-top'>
			Back to Top <span class="chevron"></span>
		</a>
	</footer>
</div>

app/views/issues/_form.html.erb
<%= render "layouts/header" %>

<div class='new-project-div'>
	<h1 class='h1'><%= issue.persisted? ? 'Edit Issue' : 'New Issue' %></h1>
	
	<% if flash[:errors] %>
		<% flash[:errors].each do |error| %>
		  <p class='auth-missing new-project-missing'><%= error %></p>
		<% end %>
		<br>
	<% end %>
	
	<%= form_for issue do |f| %>
		<div class='issue-form-line'>
			<div>
				<%= f.label :project_id, 'Project' %><br>
				<%= f.select :project_id, Project.all.map { |p| [p.name, p.id] } %>
			</div>
			<div>
				<label>Reporter</label><br>
				<%= issue.reporter.name %>
			</div>
			<div>
				<%= f.label :assignee_id, 'Assigned To' %><br>
				<%= f.select :assignee_id, User.all.map { |u| [u.name, u.id] },
					include_blank: true %>
			</div>
			<div>
				<%= f.label :priority %><br>
				<%= f.select :priority, Issue::PRIORITIES.map { |p| [p, p] } %>
			</div>
			<div>
				<%= f.label :status %><br>
				<%= f.select :status, Issue::STATUSES.map { |s| [s, s] } %>
			</div>
			<div>
				<%= f.label :due_date, 'Due Date' %><br>
				<%= f.date_field :due_date %>
			</div>
		</div>
		<%= f.label :subject %><br>
		<%= f.text_field :subject %>
		<br>
		<%= f.label :description %><br>
		<%= f.text_area :description %>
		<br>
		<%= f.submit issue.persisted? ? 'Update Issue' : 'Create Issue' %>
	<% end %>
	
	<%= button_to 'Cancel',
		issue.persisted? ? issue_path(issue) : dashboard_path,
		method: :get %>
</div>

app/views/issues/edit.html.erb
<%= render 'form', issue: @issue %>

app/views/issues/new.html.erb
<%= render 'form', issue: @issue %>

app/views/issues/show.html.erb
<%= render "layouts/header" %>

<div class='a-project-div'>
	<h1 class='h1'><%= @issue.subject %></h1>
	<div class='a-project-header'>
		<p>Project: <%= @issue.project.name %></p>
		<p>Created on <%= @issue.created_at.strftime('%B %d, %Y') %> / 
			Modified <%= time_ago_in_words(@issue.updated_at) %> ago</p>
		<div class='a-project-buttons'>
			<%= button_to 'Edit Issue', edit_issue_path(@issue), method: :get %>
			<%= button_to 'Delete Issue', issue_path(@issue), method: :delete %>
		</div>
	</div>
	<br>
	<div class='a-project-header'>
		<p>Reporter: <%= @issue.reporter.name %></p>
		<p>Assigned To: <%= @issue.assignee ? @issue.assignee.name : 'N/A' %></p>
		<p>Priority: <%= @issue.priority %></p>
		<p>Status: <%= @issue.status %></p>
		<p>Due Date: <%= @issue.due_date ? @issue.due_date.strftime('%B %d, %Y') :
			'N/A' %></p>
	</div>
	<hr>
	<p class='a-project-description'><%= @issue.description %></p>
</div>
<br>

<%= render "comments/form" %>

app/views/layouts/_header.html.erb
<header class='<%= request.path == '/' ? '' : 'header-background' %>'>
	<div class="hover-div">
		<a class='logo hover hover-1' href='/'>Trackify</a>
	</div>
	<div class='header-div'>
		<% if logged_in? %>
		  <%= button_to "Log Out", sessions_path, method: :delete %>
		<% else %>
			<div class='account-buttons'>
				<%= button_to "Log In", login_path, method: :get %>
				<%= button_to "Sign Up", signup_path, method: :get %>
		  </div>
		<% end %>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Issue Tracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'entry' %>
  </head>
	
	<body>
		<%= yield %>
	</body>
	
</html>

app/views/projects/_form.html.erb
<%= render "layouts/header" %>

<div class='new-project-div'>
	<h1 class='h1'><%= project.persisted? ? 'Edit Project' : 'New Project' %></h1>
	
	<% if flash[:errors] %>
		<% flash[:errors].each do |error| %>
		  <p class='auth-missing new-project-missing'><%= error %></p>
		<% end %>
		<br>
	<% end %>
	
	<%= form_for project do |f| %>
		<%= f.label :name %>
		<br>
		<%= f.text_field :name %>
		<br>
		<%= f.label :status %>
		<br>
		<%= f.select :status, Project::STATUSES.map { |s| [s, s] } %>
		<br>
		<%= f.label :description %>
		<br>
		<%= f.text_area :description %>
		<br>
		<%= f.submit project.persisted? ? 'Update Project' : 'Create Project' %>
	<% end %>
	
	<%= button_to 'Cancel',
		project.persisted? ? project_path(project) : dashboard_path,
		method: :get %>
</div>

app/views/projects/edit.html.erb
<%= render 'form', project: @project %>

app/views/projects/new.html.erb
<%= render 'form', project: @project %>

app/views/projects/show.html.erb
<%= render "layouts/header" %>

<div class='a-project-div'>
	<h1 class='h1'><%= @project.name %></h1>
	<div class='a-project-header'>
		<p>Status: <%= @project.status %></p>
		<p>Created on <%= @project.created_at.strftime('%B %d, %Y') %> / 
			Modified <%= time_ago_in_words(@project.updated_at) %> ago</p>
		<div class='a-project-buttons'>
			<%= button_to 'Edit Project', edit_project_path(@project), method: :get %>
			<%= button_to 'Delete Project', project_path(@project), method: :delete %>
		</div>
	</div>
	<hr>
	<p class='a-project-description'><%= @project.description %></p>
</div>
<br>
<div class='dash-projects a-project-div'>
	<hr>
	<div class='dash-projects-header'>
		<div></div>
		<h2>Issues</h2>
		<div></div>
	</div>
	<ul>
		<% @project.issues.order('updated_at desc').each do |issue| %>
			<a class='dash-project-link' href='/issues/<%= issue.id %>'>
				<%= issue.subject %>
			</a>
			<p class='dash-project-description'>
				Status: <%= issue.status %> <span class='dash-separator'>|</span> 
				Priority: <%= issue.priority %> <span class='dash-separator'>|</span> 
				Reported By: <%= User.find(issue.reporter_id).name %>
			</p>
			<hr>
		<% end %>
	</ul>
	<a class='dash-create-link dash-project-link' href='/issues/new'>
		Create New Issue
	</a>
</div>

app/views/users/new.html.erb
<%= render "layouts/header" %>

<div class='auth-div'>
	<h1 class='auth-h1'>Sign Up</h1>
	
	<% if flash[:errors] %>
		<% flash[:errors].each do |error| %>
		  <p class='auth-missing'><%= error %></p>
		<% end %>
		<br>
	<% end %>
	
	<%= form_for @user do |f| %>
		<%= f.text_field :name, placeholder: "Name" %>
		<br>
		<%= f.text_field :email, placeholder: "Email Address" %>
		<br>
		<%= f.password_field :password, placeholder: "Password" %>
		<br>
		<%= f.password_field :password_confirmation, placeholder: "Confirm Password" %>
		<br>
		<%= f.submit "Create Account" %>
	<% end %>
</div>

<footer class='home-created-by auth-footer'>Created by Peter Tran</footer>

app/views/users/show.html.erb
<h1>Welcome to the page of <%= @user.name %></h1>